--- 
changelog: 
  - 
    changes: 
      - 
        text: "Presence Timeout cannot be lower than 20"
        type: improvement
    date: May 27, 19  
    version: v4.2.2
  - 
    changes: 
      - 
        text: "History timetoken float64 to int64 conversion loss fix"
        type: bug
    date: Mar 21, 19  
    version: v4.2.1
  - 
    changes: 
      - 
        text: "Message Counts simplification (Breaking changes from the previous version)."
        type: improvement
    date: Mar 13, 19  
    version: v4.2.0
  - 
    changes: 
      - 
        text: "Implement history Message Counts"
        type: improvement
      - 
        text: "All request were secure (https), even when the Secure flag was false"
        type: bug
    date: Mar 5, 19  
    version: v4.1.7
  - 
    changes: 
      - 
        text: "Fixes for 32bit and armv7 systems"
        type: improvement
      - 
        text: "QueryParam and State in Presence Heartbeat"
        type: improvement
    date: Jan 15, 19  
    version: v4.1.6
  - 
    changes: 
      - 
        text: "Presence Heartbeat call delays itself when a Subscribe call precedes it"
        type: improvement
      - 
        text: "Heartbeats per channel"
        type: feature
    date: Dec 18, 18  
    version: v4.1.5
  - 
    changes: 
      - 
        text: "QueryParams in all API calls"
        type: feature
      - 
        text: "d in grant"
        type: feature
      - 
        text: "maxIdleConnsPerHost setting in config"
        type: feature
      - 
        text: "Max concurrent workers for Publish and Grant requests"
        type: improvement
    date: Oct 16, 18  
    version: v4.1.4
  - 
    changes: 
      - 
        text: "Multiple auth keys in grant fix"
        type: bug
      - 
        text: "Presence timetoken float64 fix"
        type: bug
    date: Sep 4, 18  
    version: v4.1.3
  - 
    changes: 
      - 
        text: "Optimizations"
        type: improvement
      - 
        text: "presence timetoken fix"
        type: bug
      - 
        text: "coverage improvements"
        type: improvement
    date: Aug 1, 18  
    version: v4.1.2
  - 
    changes: 
      - 
        text: "MessageQueueOverflowCount and PNRequestMessageCountExceededCategory"
        type: improvement
      - 
        text: "subscribeMessageWorker optimization"
        type: improvement
      - 
        text: "integration tests optimizations"
        type: improvement
    date: Jun 21, 18       
    version: v4.1.1
  - 
    changes: 
      - 
        text: "Some breaking changes from the previous v4's"
        type: improvement
      - 
        text: "config field UseHttp2 is now UseHTTP2"
        type: improvement
      - 
        text: "config field Uuid is now UUID"
        type: improvement
      - 
        text: "Get State/ WhereNow Uuid is now UUID"
        type: improvement
      - 
        text: "In Fire/Publish Ttl() is now TTL()"
        type: improvement
      - 
        text: "In Grant Ttl() is now TTL()"
        type: improvement
      - 
        text: "PNPAMEntityData Ttl is now TTL"
        type: improvement
      - 
        text: "PNAccessManagerKeyData Ttl is now TTL"
        type: improvement
      - 
        text: "TlsEnabled is now TLSEnabled in StatusResponse and ResponseInfo"
        type: improvement
      - 
        text: "Uuid is now UUID in StatusResponse and ResponseInfo"
        type: improvement
    date: Jun 18, 18        
    version: v4.1.0
  - 
    changes: 
      - 
        text: "optimizations and deadlock fixes in subscribe loop"
        type: bug
      - 
        text: "old channels got subscribed in new sub after reconnection"
        type: bug
      - 
        text: "close old subworker goroutine before starting new one"
        type: improvement
      - 
        text: "data race fixes"
        type: bug
      - 
        text: "stop tickers, state manager locks"
        type: bug
    version: v4.0.0-rc.5
  - 
    changes: 
      - 
        text: "stop heartbeat requests after unsubscribe all"
        type: bug
      - 
        text: "multiple subscribe fixes"
        type: bug
      - 
        text: "data race fixes in context"
        type: bug
      - 
        text: "fix for subscribe listener on disconnect"
        type: bug
      - 
        text: "heartbeat fixes"
        type: bug
      - 
        text: "presence heartbeat fixes"
        type: bug
      - 
        text: "subscribe to presence only channel"
        type: bug
      - 
        text: "unsubscribe from presence only channel"
        type: bug
    version: v4.0.0-rc.4
  - 
    changes: 
      - 
        text: "Reconnection fixes"
        type: bug
    version: v4.0.0-rc.3
  - 
    changes: 
      - 
        text: "auth fix"
        type: bug
      - 
        text: "Signature does not match fix when both secret key and auth is set"
        type: bug
      - 
        text: cleanup
        type: improvement
      - 
        text: "integration tests fixes for the changes done on auth"
        type: improvement
    version: v4.0.0-rc.2
  - 
    changes: 
      - 
        text: "set state refactor fix"
        type: bug
    version: v4.0.0-rc.1
  - 
    changes: 
      - 
        text: "Subscribe with state"
        type: improvement
    version: v4.0.0-beta.8
  - 
    changes: 
      - 
        text: "cipher improvements"
        type: improvement
    version: v4.0.0-beta.7
  - 
    changes: 
      - 
        text: "Fire, Fetch, HereNowRequest"
        type: improvement
    version: v4.0.0-beta.6
  - 
    changes: 
      - 
        text: "add subscribe builder"
        type: improvement
    version: v4.0.0-beta.5
  - 
    changes: 
      - 
        text: "add Telemetry Manager"
        type: improvement
    version: v4.0.0-beta.4
  - 
    changes: 
      - 
        text: "add Destroy() method"
        type: improvement
    version: v4.0.0-beta.3
  - 
    changes: 
      - 
        text: "add reconnection manager"
        type: impovement
      - 
        text: "rename list, remove, add, delete channel of channel groups"
        type: impovement
      - 
        text: "fix comma encoding"
        type: bug
      - 
        text: "fix signature"
        type: bug
    version: v4.0.0-beta.2
  - 
    changes: 
      - 
        text: "initial beta"
        type: impovement
    version: v4.0.0-beta
features: 
  access: 
    - ACCESS-GRANT
    - ACCESS-GRANT-MANAGE
    - ACCESS-GRANT-DELETE
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups: 
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence: 
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-GET-STATE
    - PRESENCE-SET-STATE
    - PRESENCE-HEARTBEAT
    - PRESENCE-HEARTBEAT-ON-DEMAND
    - PRESENCE-HEARTBEAT-THROTTLED
    - PRESENCE-HERE-NOW-REFRESH
  publish: 
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  push: 
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  storage: 
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
    - STORAGE-MESSAGE-COUNT
  subscribe: 
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNEL-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-WITH-USERSTATE
    - SUBSCRIBE-PUBSUB-V2
  time: 
    - TIME-TIME
  unsubscribe: 
    - UNSUBSCRIBE-ALL
    - UNSUBSCRIBE-SUPPRESS-LEAVE-EVENTS
  others:
    - PN-OTHER-PROCESSING
    - TELEMETRY
    - QUERY-PARAM
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED  
name: go
schema: 1
scm: github.com/pubnub/go
supported-platforms: 
  - 
    editors: 
      - "1.9.7"
      - "1.10.3"
      - "1.11.1"
      - "1.12.1"
    platforms: 
      - "FreeBSD 8-STABLE or later, amd64, 386"
      - "Linux 2.6 or later, amd64, 386."
      - "Mac OS X 10.8 or later, amd64"
      - "Windows 7 or later, amd64, 386"
    version: "PubNub Go SDK"
version: v4.2.2
