--- 
changelog: 
  - 
    changes: 
      - 
        text: "Some breaking changes from the previous v4's"
        type: improvement
      - 
        text: "config field UseHttp2 is now UseHTTP2"
        type: improvement
      - 
        text: "config field Uuid is now UUID"
        type: improvement
      - 
        text: "Get State/ WhereNow Uuid is now UUID"
        type: improvement
      - 
        text: "In Fire/Publish Ttl() is now TTL()"
        type: improvement
      - 
        text: "In Grant Ttl() is now TTL()"
        type: improvement
      - 
        text: "PNPAMEntityData Ttl is now TTL"
        type: improvement
      - 
        text: "PNAccessManagerKeyData Ttl is now TTL"
        type: improvement
      - 
        text: "TlsEnabled is now TLSEnabled in StatusResponse and ResponseInfo"
        type: improvement
      - 
        text: "Uuid is now UUID in StatusResponse and ResponseInfo"
        type: improvement
    version: v4.1.0
  - 
    changes: 
      - 
        text: "optimizations and deadlock fixes in subscribe loop"
        type: bug
      - 
        text: "old channels got subscribed in new sub after reconnection"
        type: bug
      - 
        text: "close old subworker goroutine before starting new one"
        type: improvement
      - 
        text: "data race fixes"
        type: bug
      - 
        text: "stop tickers, state manager locks"
        type: bug
    version: v4.0.0-rc.5
  - 
    changes: 
      - 
        text: "stop heartbeat requests after unsubscribe all"
        type: bug
      - 
        text: "multiple subscribe fixes"
        type: bug
      - 
        text: "data race fixes in context"
        type: bug
      - 
        text: "fix for subscribe listener on disconnect"
        type: bug
      - 
        text: "heartbeat fixes"
        type: bug
      - 
        text: "presence heartbeat fixes"
        type: bug
      - 
        text: "subscribe to presence only channel"
        type: bug
      - 
        text: "unsubscribe from presence only channel"
        type: bug
    version: v4.0.0-rc.4
  - 
    changes: 
      - 
        text: "Reconnection fixes"
        type: bug
    version: v4.0.0-rc.3
  - 
    changes: 
      - 
        text: "auth fix"
        type: bug
      - 
        text: "Signature does not match fix when both secret key and auth is set"
        type: bug
      - 
        text: cleanup
        type: improvement
      - 
        text: "integration tests fixes for the changes done on auth"
        type: improvement
    version: v4.0.0-rc.2
  - 
    changes: 
      - 
        text: "set state refactor fix"
        type: bug
    version: v4.0.0-rc.1
  - 
    changes: 
      - 
        text: "Subscribe with state"
        type: improvement
    version: v4.0.0-beta.8
  - 
    changes: 
      - 
        text: "cipher improvements"
        type: improvement
    version: v4.0.0-beta.7
  - 
    changes: 
      - 
        text: "Fire, Fetch, HereNowRequest"
        type: improvement
    version: v4.0.0-beta.6
  - 
    changes: 
      - 
        text: "add subscribe builder"
        type: improvement
    version: v4.0.0-beta.5
  - 
    changes: 
      - 
        text: "add Telemetry Manager"
        type: improvement
    version: v4.0.0-beta.4
  - 
    changes: 
      - 
        text: "add Destroy() method"
        type: improvement
    version: v4.0.0-beta.3
  - 
    changes: 
      - 
        text: "add reconnection manager"
        type: impovement
      - 
        text: "rename list, remove, add, delete channel of channel groups"
        type: impovement
      - 
        text: "fix comma encoding"
        type: bug
      - 
        text: "fix signature"
        type: bug
    version: v4.0.0-beta.2
  - 
    changes: 
      - 
        text: "initial beta"
        type: impovement
    version: v4.0.0-beta
features: 
  access: 
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups: 
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  others: 
    - TELEMETRY
  presence: 
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-GET-STATE
    - PRESENCE-SET-STATE
    - PRESENCE-HEARTBEAT
    - PRESENCE-HERE-NOW-REFRESH
  publish: 
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  push: 
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  storage: 
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
    - STORAGE-DELETE-MESSAGES
    - STORAGE-FETCH-MESSAGES
  subscribe: 
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNEL-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-WITH-USERSTATE
    - SUBSCRIBE-PUBSUB-V2
  time: 
    - TIME-TIME
  unsubscribe: 
    - UNSUBSCRIBE-ALL
    - UNSUBSCRIBE-SUPPRESS-LEAVE-EVENTS
name: go
schema: 1
scm: github.com/pubnub/go
supported-platforms: 
  - 
    editors: 
      - "1.7.1"
      - "1.7.3"
      - "1.7.4"
      - 1.8
      - 1.9
      - "1.9.7"
      - "1.10.3"
    platforms: 
      - "FreeBSD 8-STABLE or later, amd64, 386"
      - "Linux 2.6 or later, amd64, 386."
      - "Mac OS X 10.8 or later, amd64"
      - "Windows 7 or later, amd64, 386"
    version: "PubNub Go SDK"
version: v4.1.0
