package pubnub

type PNStatusCategory int
type PNOperationType int

const (
	PNUnknownCategory PNStatusCategory = 1 << iota
	PNAcknowledgmentCategory
	PNAccessDeniedCategory
	PNTimeoutCategory
	PNNetworkIssuesCategory
	PNConnectedCategory
	PNReconnectedCategory
	PNUnsubscribedCategory
	PNDisconnectedCategory
	PNUnexpectedDisconnectCategory
	PNCancelledCategory
	PNBadRequestCategory
	PNMalformedFilterExpressionCategory
	PNMalformedResponseCategory
	PNDecryptionErrorCategory
	PNTLSConnectionFailedCategory
	PNTLSUntrustedCertificateCategory
	PNRequestMessageCountExceededCategory
)

const (
	PNSubscribeOperation PNOperationType = 1 << iota
	PNUnsubscribeOperation
	PNPublishOperation
	PNHistoryOperation
	PNFetchMessagesOperation
	PNWhereNowOperation
	PNHereNowOperation
	PNHeartBeatOperation
	PNSetStateOperation
	PNGetStateOperation
	PNAddChannelsToChannelGroupOperation
	PNRemoveChannelFromChannelGroupOperation
	PNChannelGroupOperation
	PNRemoveGroupOperation
	PNChannelsForGroupOperation
	PNPushNotificationsEnabledChannelsOperation
	PNAddPushNotificationsOnChannelsOperation
	PNRemovePushNotificationsFromChannelsOperation
	PNRemoveAllPushNotificationsOperation
	PNTimeOperation
	PNAccessManagerGrant
	PNAccessManagerRevoke
)
