
name: run_acceptance_tests

on: [push]

jobs:
  build:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Checkout mock-server action
        uses: actions/checkout@v3
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: v1
          token: ${{ secrets.GH_TOKEN }}
          path: .github/.release/actions
      - name: Run mock server action
        uses: ./.github/.release/actions/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Go 1.19.4
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
          cache: true
      - name: Run acceptance tests (optional)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && @beta" -format "junit:beta.xml"
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && ~@beta" -format "junit:main.xml"
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: acceptance-test-reports
          path: |
            ./tests/contract/beta.xml
            ./tests/contract/main.xml
          retention-days: 7
