
name: run_acceptance_tests

on: [push]

jobs:
  build:
    name: Perform Acceptance BDD tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: client-engineering-deployment-tools
      - name: Run mock server action
        uses: ./client-engineering-deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run acceptance tests (optional)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && @beta" -format "junit:beta.xml"
        continue-on-error: true
      - name: Run acceptance tests (required)
        run: |
          cd tests/contract
          go test -path ../../sdk-specifications/features -tagsFilter "~@skip && ~@na=go && ~@beta" -format "junit:main.xml"
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: acceptance-test-reports
          path: |
            ./tests/contract/beta.xml
            ./tests/contract/main.xml
          retention-days: 7
